development:
  host: localhost
  database: nerd_companion_development

test:
  host: localhost
  database: nerd_companion_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>
