development:
  host: localhost
  database: nerd_composer_development

test:
  host: localhost
  database: nerd_composer_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
